### ISSUE TITLE
Xetha Project Development Milestone

### ISSUE THREAD

**Issue by ehcac1024** [astzoid/xetha#79]
- [x] Working Discord Bot (xanatha)
- [x] Working Leveling System (xanatha) 
- [x] Working Backend (cathy)
- [x] Working Frontend (athena)

- [ ] WebSocket API Communication Between `athena` <----> `cathy` <----> `xanatha` (PR #78)

- [ ] Continuous Deployments via Github Actions CI/CD DevOps (ETA 1 day)
  - [ ] `xanatha` on vps
  - [ ] `cathy` on vps
  - [ ] `athena` on netlify

- [ ] Migrate all pages from branch `athena-1` to the main branch. (ETA 1-2 Days)
  - [ ] Terms of Service
  - [ ] Privacy Policy
  - [ ] Commands
  - [ ] Guild Selector

- [ ] Major refactoring on `xanatha` (ETA 1-3 days or more if needed)
  - [ ] Development of our private discord library `disclosure.js` which uses `discord.js`, `discord.js-light` and useful Plug'n Play dependencies to improve performance to scale up to the moon.
  - [ ] Using `disclosure.js`

- [ ] Completing the backend service `cathy` (ETA 2-4 days or more if needed)
  - [ ] Websocket Payload Data Validation to validate incoming requests to update guild data from the website dashboard
  - [ ] Server Listing Pagination. (This is an opt-in opt-out feature for servers)
  - [ ] Updating Guild Data

- [ ] Completing the website `athena` (ETA 2 weeks - 4 weeks or more if needed)
  - [ ] Status Page (List of shards currently online)
  - [ ] Server Listing Page with Pagination, Searching, Search by Tag or keywords in description.
  - [ ] Refactoring the Guild Selector Page to match with the Dashboard Pages
  - [ ] Dashboard Pages
    - [ ] General Settings
    - [ ] Server Listing
    - [ ] Leveling
    - [ ] Moderation
    - [ ] Welcome/Farewell
    - [ ] Tickets
    - [ ] Logging

- [ ] Completing the actual bot `xanatha` (ETA 2-3 weeks or more if needed)
  - [ ] Welcome/Farewell
  - [ ] Logging
  - [ ] Moderation
  - [ ] Tickets
  - [ ] Server Tags

- [ ] Finishing things up.
- [ ] Testing every feature
- [ ] Project released to public.

Next... (Still a secret)
    
This issue will be updated overtime
